# Generated by Django 3.0 on 2021-09-24 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oc_lettings_site', '0002_auto_20210924_1016'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
